apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: psj83orof-python 
  janus-idp.io/tekton: psj83orof-python
  backstage.io/kubernetes-id: psj83orof-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: psj83orof-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  