apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: psj83orof-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: psj83orof-python 
  name: psj83orof-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: psj83orof-python 
